server:
  port: 8080

spring:
  application:
    name: workflow-engine

workflow:
  enabled: true
  base-package: com.niko.langchain4jworkflow
  async:
    enabled: true
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
  cache:
    enabled: true
    max-size: 10000
    default-ttl: 10m
  monitor:
    enabled: true
    log-input: false
    log-output: true
  ai:
    openai-api-key: ${OPENAI_API_KEY}
    max-tokens: 1000
    temperature: 0.7
    timeout: 30s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always